export const SEO_REGIONS = [
  { slug: 'gangnam',  name: '강남' },
  { slug: 'seoul',    name: '서울' },
  { slug: 'busan',    name: '부산' },
  { slug: 'daegu',    name: '대구' },
  { slug: 'incheon',  name: '인천' },
  { slug: 'suwon',    name: '수원' },
  { slug: 'daejeon',  name: '대전' },
  { slug: 'gwangju',  name: '광주' },
  { slug: 'ulsan',    name: '울산' },
  { slug: 'jeonju',   name: '전주' },
  { slug: 'cheongju', name: '청주' },
  { slug: 'changwon', name: '창원' },
  { slug: 'pohang',   name: '포항' },
  { slug: 'jeju',     name: '제주' },
] as const;

export const PROVINCES = [
  { key: 'seoul', name: '서울' },
  { key: 'gyeonggi', name: '경기' },
  { key: 'incheon', name: '인천' },
  { key: 'busan', name: '부산' },
  { key: 'daegu', name: '대구' },
  { key: 'daejeon', name: '대전' },
  { key: 'gwangju', name: '광주' },
  { key: 'ulsan', name: '울산' },
  { key: 'gangwon', name: '강원' },
  { key: 'chungbuk', name: '충북' },
  { key: 'chungnam', name: '충남' },
  { key: 'jeonbuk', name: '전북' },
  { key: 'jeonnam', name: '전남' },
  { key: 'gyeongbuk', name: '경북' },
  { key: 'gyeongnam', name: '경남' },
  { key: 'jeju', name: '제주' },
  { key: 'sejong', name: '세종' },
];

export const DISTRICTS: Record<string, string[]> = {
  seoul: ['강남구', '서초구', '송파구', '마포구', '영등포구', '강서구', '용산구', '종로구', '기타'],
  gyeonggi: ['수원시', '성남시', '고양시', '용인시', '부천시', '안산시', '안양시', '남양주시', '화성시', '기타'],
  incheon: ['중구', '동구', '미추홀구', '연수구', '남동구', '부평구', '계양구', '서구', '강화군', '옹진군'],
  busan: ['해운대구', '부산진구', '수영구', '동래구', '남구', '기타'],
  daegu: ['중구', '수성구', '달서구', '동구', '북구', '기타'],
  daejeon: ['유성구', '서구', '중구', '동구', '대덕구'],
  gwangju: ['상무지구', '동구', '서구', '남구', '북구', '광산구'],
  ulsan: ['남구', '중구', '동구', '북구', '울주군'],
  gangwon: ['춘천시', '원주시', '강릉시', '속초시', '기타'],
  chungbuk: ['청주시', '충주시', '제천시', '기타'],
  chungnam: ['천안시', '아산시', '서산시', '당진시', '기타'],
  jeonbuk: ['전주시', '익산시', '군산시', '기타'],
  jeonnam: ['목포시', '여수시', '순천시', '광양시', '기타'],
  gyeongbuk: ['포항시', '구미시', '경주시', '경산시', '기타'],
  gyeongnam: ['창원시', '김해시', '진주시', '양산시', '거제시', '기타'],
  jeju: ['제주시', '서귀포시'],
  sejong: ['세종시'],
};
